= Intelligent LED library for Arduino =

This library is designed to make the use of LEDs as simple as possible. After creating the LED and asigning a port number, the state simply can be changed to on, off, blink or flash. When constructed with two ports a multicolor LED can be used in the same way with the additional color method. A simple update() in the main loop ensures the correct blink and flash timing.  

For more information about this library please visit us at
http://nibble-arts.org

== License ==

Copyright (c) Nibble-arts. All right reserved.
Copyright (c) Thomas Winkler. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA